# SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
#
# SPDX-License-Identifier: Apache-2.0

github: vhanda
bitcoin: bc1qe97tgx5sndlk6ynz0e7na0hseevwy5uydk369r
ethereum: 0xD4964e0E9A8Ca8A0be8db717690D888Aa5e92DcD
