name: gitjournal
description: A Note Taking App Built on top of Git
version: 1.82.0+10

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.2"

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dart_git:
    git: https://github.com/GitJournal/dart-git.git
    # path: ../gitjournal/dart-git
  git_bindings:
    #path: /Users/vishesh/src/gitjournal/git_bindings
    git: https://github.com/GitJournal/git_bindings.git
  icloud_documents_path:
    git: https://github.com/GitJournal/icloud_documents_path.git
  auto_size_text: ^3.0.0-nullsafety.0
  badges: ^2.0.1
  connectivity_plus: ^1.0.6
  cryptography: ^2.0.5
  device_info_plus: ^2.1.0
  dots_indicator: ^2.0.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  email_validator: ^2.0.1
  equatable: ^2.0.0
  file_picker: ^4.0.2
  filesystem_picker: ^2.0.0-nullsafety.0 # for directories
  fimber: ^0.6.1
  flutter_cache_manager: ^3.0.1
  flutter_email_sender: ^5.0.2
  flutter_emoji:
    git: https://github.com/cek-cek/flutter-emoji
  flutter_markdown: ^0.6.1
  flutter_runtime_env: ^0.0.4
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.21.0+1
  font_awesome_flutter: ^9.0.0
  function_types: ^0.1.0
  google_fonts: ^2.1.0
  http: ^0.13.1
  image_picker: ^0.8.4+1
  in_app_purchase: ^0.5.2
  intl: ^0.17.0
  launch_review: ^3.0.1
  mutex: ^3.0.0
  org_flutter: ^1.4.0
  package_info_plus: ^1.0.4
  path: ^1.8.0
  permission_handler: ^6.1.1
  photo_view:
    git:
      url: https://github.com/karvulf/photo_view.git
      ref: bugfix/flutter-2.5-update
  provider: ^6.0.1
  quick_actions: ^0.6.0+3
  receive_sharing_intent: ^1.4.5
  sentry_flutter: ^6.0.0
  share_plus: ^2.1.4
  shared_preferences: ^2.0.5
  #ssh_key: ^0.6.0
  stack_trace: ^1.10.0
  synchronized: ^3.0.0
  time: ^2.0.0
  timeago: ^3.1.0
  url_launcher: ^6.0.3
  uuid: ^3.0.4
  yaml: ^3.1.0
  yaml_serializer: ^0.0.11
  collection: ^1.15.0-nullsafety.4
  flex_color_scheme: ^2.1.1
  fs_shim: ^2.0.1+2
  grpc: ^3.0.0
  protobuf: ^2.0.0
  universal_io: ^2.0.4
  sprintf: ^6.0.0
  recase: ^4.0.0
  supabase_flutter: ^0.2.5
  nested: ^1.0.0
  language_picker: ^0.4.1
  flutter_login:
    git:
      url: https://github.com/NearHuscarl/flutter_login.git
      ref: develop
  android_external_storage: ^0.1.0
  # background_fetch:
  #   git: https://github.com/Fishbowler/flutter_background_fetch.git
  timeline_tile: ^2.0.0
  community_material_icon: ^5.9.55
  google_api_availability: ^3.0.1
  carousel_slider: ^4.0.0
  table_calendar: ^3.0.3
  openssh_ed25519:
    path: packages/openssh_ed25519

dev_dependencies:
  #flutter_driver:
  #  sdk: flutter
  flutter_test:
    sdk: flutter
  benchmark_harness: ^2.0.0
  # bonsoir: ^1.0.0
  flutter_launcher_icons:
    git: https://github.com/dirkbo/flutter_launcher_icons
  # flutter_webview_plugin: ^0.3.11
  import_sorter: ^4.6.0
  # multicast_dns: ^0.3.0
  #screenshots: ^2.1.1
  test: ^1.16.5
  build_runner: ^2.1.2
  dashbook: ^0.1.3
  dart_code_metrics: ^4.3.3
  hive_generator: ^1.1.0
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - "assets/icon/icon.png"
    - "assets/icon/github-icon.png"
    - "assets/icon/gitlab-icon.png"
    - "assets/OnBoardingMarkdown.png"
    - "assets/OnBoardingGitProviders.png"
    - "assets/langs/"
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  ios: true
  macos: true
  windows: false
  linux: false

import_sorter:
  comments: false
