# SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
#
# SPDX-License-Identifier: Apache-2.0

version: 2.1
jobs:
  build_ios:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Install gpg
          command: brew install gnupg git-crypt md5sha1sum wget gnu-sed
      - run:
          name: Install Flutter
          command: ./scripts/ios_install_flutter.sh
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=flutter/bin:$PATH" >> $BASH_ENV
      - run:
          name: Unlock Secrets
          command: ./scripts/decrypt_secrets.sh
      - run:
          name: Setup GitJournal Build Env
          command: ./flutter/bin/cache/dart-sdk/bin/dart ./scripts/setup_env.dart
      - run:
          name: Pub get
          command: flutter pub get
      - run:
          name: Test
          command: flutter test
      - run:
          name: Setup provisioning profile
          command: ./scripts/add_ios_keys.sh
      - run:
          name: Build App
          command: ./scripts/build_ios.sh || true

workflows:
  version: 2
  build_all:
    jobs:
      - build_ios
